/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.x */

#include "cot.pb.h"
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cot_CotMessage, cot_CotMessage, AUTO)
PB_BIND(cot_OTRoundInit, cot_OTRoundInit, AUTO)
PB_BIND(cot_OTRoundResponse, cot_OTRoundResponse, AUTO)
PB_BIND(cot_OTEncryptedMsgs, cot_OTEncryptedMsgs, AUTO)
PB_BIND(cot_ShareResult, cot_ShareResult, AUTO)
PB_BIND(cot_ErrorMsg, cot_ErrorMsg, AUTO)
