/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.x from cot.proto */

#ifndef PB_COT_COT_PB_H_INCLUDED
#define PB_COT_COT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

// Enum defs
typedef enum _cot_MessageType {
    cot_MessageType_UNKNOWN = 0,
    cot_MessageType_OT_ROUND_INIT = 1,
    cot_MessageType_OT_ROUND_RESPONSE = 2,
    cot_MessageType_OT_ENCRYPTED_MSGS = 3,
    cot_MessageType_SHARE_RESULT = 4,
    cot_MessageType_ERROR = 5
} cot_MessageType;

// Struct defs
typedef struct _cot_OTRoundInit {
    uint32_t round_index;
    pb_callback_t point_a;  /* 33-byte compressed EC point */
} cot_OTRoundInit;

typedef struct _cot_OTRoundResponse {
    uint32_t round_index;
    pb_callback_t point_b;  /* 33-byte compressed EC point */
} cot_OTRoundResponse;

typedef struct _cot_OTEncryptedMsgs {
    uint32_t round_index;
    pb_callback_t e0;  /* IV(16B) || ciphertext */
    pb_callback_t e1;  /* IV(16B) || ciphertext */
} cot_OTEncryptedMsgs;

typedef struct _cot_ShareResult {
    pb_callback_t share;  /* 32-byte additive share */
} cot_ShareResult;

typedef struct _cot_ErrorMsg {
    pb_callback_t description;
} cot_ErrorMsg;

typedef struct _cot_CotMessage {
    cot_MessageType message_type;
    pb_size_t which_payload;
    union {
        cot_OTRoundInit ot_round_init;
        cot_OTRoundResponse ot_round_response;
        cot_OTEncryptedMsgs ot_encrypted_msgs;
        cot_ShareResult share_result;
        cot_ErrorMsg error;
    } payload;
} cot_CotMessage;

#ifdef __cplusplus
extern "C" {
#endif

// Helper constants for oneofs
#define cot_CotMessage_ot_round_init_tag 2
#define cot_CotMessage_ot_round_response_tag 3
#define cot_CotMessage_ot_encrypted_msgs_tag 4
#define cot_CotMessage_share_result_tag 5
#define cot_CotMessage_error_tag 6

// Initializer values for message structs
#define cot_OTRoundInit_init_default          {0, {{NULL}, NULL}}
#define cot_OTRoundResponse_init_default      {0, {{NULL}, NULL}}
#define cot_OTEncryptedMsgs_init_default      {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define cot_ShareResult_init_default          {{{NULL}, NULL}}
#define cot_ErrorMsg_init_default             {{{NULL}, NULL}}
#define cot_CotMessage_init_default           {_cot_MessageType_MIN, 0, {cot_OTRoundInit_init_default}}

#define cot_OTRoundInit_init_zero             {0, {{NULL}, NULL}}
#define cot_OTRoundResponse_init_zero         {0, {{NULL}, NULL}}
#define cot_OTEncryptedMsgs_init_zero         {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define cot_ShareResult_init_zero             {{{NULL}, NULL}}
#define cot_ErrorMsg_init_zero                {{{NULL}, NULL}}
#define cot_CotMessage_init_zero              {_cot_MessageType_MIN, 0, {cot_OTRoundInit_init_zero}}

// Field tags for manual encoding
#define cot_OTRoundInit_round_index_tag       1
#define cot_OTRoundInit_point_a_tag           2
#define cot_OTRoundResponse_round_index_tag   1
#define cot_OTRoundResponse_point_b_tag       2
#define cot_OTEncryptedMsgs_round_index_tag   1
#define cot_OTEncryptedMsgs_e0_tag            2
#define cot_OTEncryptedMsgs_e1_tag            3
#define cot_ShareResult_share_tag             1
#define cot_ErrorMsg_description_tag          1
#define cot_CotMessage_message_type_tag       1
#define cot_CotMessage_ot_round_init_tag      2
#define cot_CotMessage_ot_round_response_tag  3
#define cot_CotMessage_ot_encrypted_msgs_tag  4
#define cot_CotMessage_share_result_tag       5
#define cot_CotMessage_error_tag              6

// Struct field encoding specifications
#define cot_OTRoundInit_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, round_index, 1) \
X(a, CALLBACK, SINGULAR, BYTES, point_a, 2)

#define cot_OTRoundInit_CALLBACK pb_default_field_callback
#define cot_OTRoundInit_DEFAULT NULL

#define cot_OTRoundResponse_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, round_index, 1) \
X(a, CALLBACK, SINGULAR, BYTES, point_b, 2)

#define cot_OTRoundResponse_CALLBACK pb_default_field_callback
#define cot_OTRoundResponse_DEFAULT NULL

#define cot_OTEncryptedMsgs_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, round_index, 1) \
X(a, CALLBACK, SINGULAR, BYTES, e0, 2) \
X(a, CALLBACK, SINGULAR, BYTES, e1, 3)

#define cot_OTEncryptedMsgs_CALLBACK pb_default_field_callback
#define cot_OTEncryptedMsgs_DEFAULT NULL

#define cot_ShareResult_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, share, 1)

#define cot_ShareResult_CALLBACK pb_default_field_callback
#define cot_ShareResult_DEFAULT NULL

#define cot_ErrorMsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, description, 1)

#define cot_ErrorMsg_CALLBACK pb_default_field_callback
#define cot_ErrorMsg_DEFAULT NULL

#define cot_CotMessage_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UENUM, message_type, 1) \
X(a, STATIC, ONEOF, MESSAGE, (payload,ot_round_init,payload.ot_round_init), 2) \
X(a, STATIC, ONEOF, MESSAGE, (payload,ot_round_response,payload.ot_round_response), 3) \
X(a, STATIC, ONEOF, MESSAGE, (payload,ot_encrypted_msgs,payload.ot_encrypted_msgs), 4) \
X(a, STATIC, ONEOF, MESSAGE, (payload,share_result,payload.share_result), 5) \
X(a, STATIC, ONEOF, MESSAGE, (payload,error,payload.error), 6)

#define cot_CotMessage_CALLBACK NULL
#define cot_CotMessage_DEFAULT NULL

extern const pb_msgdesc_t cot_CotMessage_msg;
extern const pb_msgdesc_t cot_OTRoundInit_msg;
extern const pb_msgdesc_t cot_OTRoundResponse_msg;
extern const pb_msgdesc_t cot_OTEncryptedMsgs_msg;
extern const pb_msgdesc_t cot_ShareResult_msg;
extern const pb_msgdesc_t cot_ErrorMsg_msg;

// for backwards compatibility
#define cot_CotMessage_fields &cot_CotMessage_msg
#define cot_OTRoundInit_fields &cot_OTRoundInit_msg
#define cot_OTRoundResponse_fields &cot_OTRoundResponse_msg
#define cot_OTEncryptedMsgs_fields &cot_OTEncryptedMsgs_msg
#define cot_ShareResult_fields &cot_ShareResult_msg
#define cot_ErrorMsg_fields &cot_ErrorMsg_msg

/* Maximum encoded size of messages */
/* cot_OTRoundInit_size depends on runtime parameters */
/* cot_OTRoundResponse_size depends on runtime parameters */
/* cot_OTEncryptedMsgs_size depends on runtime parameters */
/* cot_ShareResult_size depends on runtime parameters */
/* cot_ErrorMsg_size depends on runtime parameters */
/* cot_CotMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* PB_COT_COT_PB_H_INCLUDED */
